language: node_js

node_js:
  - 0.8
  - 0.7

before_install:
 - sudo apt-get remove chromium firefox mongodb-10gen
 - sudo apt-get install texlive
# - sudo apt-add-repository -y ppa:texlive-backports/ppa
# - sudo apt-get update
# - sudo apt-get install texlive

script:
  - make
